### ISSUE TITLE
Guide for installation? 

### ISSUE THREAD

**Issue by perisicnikola37** [alperenkucukali/samplebank-microservices#1]
Are there any installation instructions? Why isn't there a wiki page related to this?

I started the project, but I suggest that you make a guide so that more people can see this project :)

**Comment by alperenkucukali** [comment]
> Are there any installation instructions? Why isn't there a wiki page related to this?
> 
> I started the project, but I suggest that you make a guide so that more people can see this project :)

I've copied the content from the README page to create a wiki page for now. I will update it as I find time. Thank you for the suggestion 👍🏼
