### ISSUE TITLE
Missing PR(pull request) labels [bug, fix, enhancement, dependencies etc.]

### ISSUE THREAD

**Issue by perisicnikola37** [alperenkucukali/samplebank-microservices#10]
Feature Request: Create PR Labels

Create a standardized set of labels for pull requests (PRs) to improve the organization, prioritization, and clarity of contributions. Labels will help categorize PRs based on their type, urgency, or scope, making the review and merging process smoother.

**Comment by alperenkucukali** [comment]
The default labels are already included. I've added your suggestions too 👍🏼
